---
CNV:
    pileup:
        MAPQ: 20
        Q: 25
    hetSNP:
        normalVAF: [0.2,0.8]
        minDepth: 15
    coverage:
        threads: 6
        minCov: 0
        minPONcov: 50
        maxPONstd: 50
        GCnormalize: True
    combine:
        threads: 6
    PONcoverage:
        threads: 4
        minCov: 0 # start with no coverage to 
        minVAF: 0.05 # min total VAF to be stored in PON snp file
        minDepth: 50
        stdFactor: 2  # only exonPositions straighing within std_factor * std around meanCoverage are kept
    filter:
        cov:
            GCrange: [0.15, 0.85] # range of GCratios
            minPONcov: 30
            maxPONstd: 35
        snp:
            # minDepth: 15    # for VAF SNP
            # minVAF: 0.05
            maxPONVAF: 0.45
            map30_0: 0
            map50_0: 0.3
            map75_1: 0.3
            map100_2: 0.5
            maxFallSNP: 0.01
            maxSNPdensity: 0.02
            # minoffVAF: 0
    rolling:
        cov:
            normalize: False
            debug: False # show more output and include L and R columns
            diff_exp: 4  # the exponent for the diff function --> higher values make steeper Diff peaks
            ddof: 0     # set the degree of freedom (0 seems better)
            LLH:
                center_range: [-0.5, 0.5]   # the mean of the gaussian is taken from log2ratios within center range
                sigma_factor: 0.9     # determines the spread of the center gaussian - sigma of center gaussian is std * sigma_factor
            data:  # list the cols you want to perform rolling window computation on
                log2ratio:
                    mean: 250    # list the aggregation function and the window size
                covLLH:
                    sum: 250
        snp:
            normalize: True
            debug: False # show more output and include L and R columns
            diff_exp: 4  # the exponent for the diff function --> higher values make steeper Diff peaks
            ddof: 0     # set the degree of freedom (0 seems better)
            LLH:
                center_range: [-0.5, 0.5]   # the mean of the gaussian is taken from log2ratios within center range
                sigma_factor: 0.9     # determines the spread of the center gaussian - sigma of center gaussian is std * sigma_factor
            data:  # list the cols you want to perform rolling window computation on
                SNPdensity: 5    # this is a custom function 
                log2ratio:
                    mean: 250    # list the aggregation functions and the window size
                covLLH:
                    sum: 250
    ascat:
        gender: XX
        ascat_penalty: [25,75]
        gamma: 1
        calculate_normal: False
