---
paths:
    static: /fast/groups/ag_damm/work/ref/
envs: env # the folder of the env-files (MacOS requires different environments)
#### REF SECTION ###############
ref:
    build: hg38
    hg19:
        genome_path: genome/gatk/b37
        genome: genome/gatk/b37/human_g1k_v37.fasta
        genome_split: genome/gatk/b37/split
        candidates: /fast/users/szyskam_c/work/utils/bulltools/known_sites/candidate_genes_aml.txt
        dbsnp: annotation/gatk/b37/dbsnp_138.b37.vcf
        dbsnp_all: annotation/gatk/b37/All_20180423.vcf
        dbsnp_common: annotation/gatk/b37/common_all_20180423.vcf
        gold_standard_indels: annotation/gatk/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
        phase1k_indels: annotation/gatk/b37/1000G_phase1.indels.b37.vcf
        # bed_file: bed_files/SureSelect/hg19/SS_HAEv6r2_hg19_Covered_nochr.bed
        # bed_file_pad: bed_files/SureSelect/hg19/SS_HAEv6r2_hg19_Padded_nochr.bed
    hg38:
        genome_path: genome/gatk/hg38/
        genome: genome/gatk/hg38/hg38.fasta
        genome_split: genome/gatk/hg38/split
        bed_file: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Covered.bed
        bed_file_pad: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Padded.bed
        dbsnp_split: annotation/gatk/hg38/HAEv7split
#### TOOLS SECTION ##############
tools:
    annovar: perl /fast/users/szyskam_c/tools/annovar2019
mpileup:
    Q: 25   # base quality
    MAPQ: 20 # -q in pileup
varscan:
    threads: 8
    vcf: true # VCF output is necessary for left-alignment
    min-coverage: 1
    min-var-freq: 0.01
    min-freq-for-hom: 0.75
    normal-purity: 0.95
    tumor-purity: 0.8
    p-value: 0.99
    somatic-p-value: 0.05
annovar:
    threads: 10
    humandb: annotation/annovar/humandb # path to humandb relative to static
    annofiles:
        - refGene
        - ensGene34
        - cytoBand
        - genomicSuperDups
        ##### POPULATIONS ########
        # - esp6500_all
        # - esp6500siv2_all  #
        # - 1000g2010nov_all
        # - 1000g2014oct_all
        # - snp138
        # - snp138NonFlagged
        - avsnp150_HAEv7
        # - gnomad_exome_all
        - gnomad30_HAEv7
        - dbsnp153_HAEv7
        # - gnomad_af.lna # not indexed
        # - exac03_all
        # - dbscsnv11
        # - snp131
        # - snp131NonFlagged
        ##### CLINICAL DATA ###### 
        - cosmic70
        - cosmic92
        - icgc29
        # - clinvar_20150629
        # - clinvar_20170905
        # - clinvar2019_short
        - clinvar2020_short
        ##### PREDICTIONS ########
        # - ljb26_all
        # - dbnsfp30a
        - dbnsfp35a_HAEv7  # 70 columns packed with predictions !!
        - spidex
primer3:  # is applied after filter step 1
    threads: 10
    use_primer_list: ''  # not established yet
    params:
        size_range: [120, 220] # targeted amplicon size
        seq_len: 500 # the length of the query sequence to find primers in
        center_offSet: 5 #  how much offSet primer pairs can have
        prod_size_min: 120
        prod_size_max: 220
FisherStrand:
    threads: 20
HDR:
    threads: 20 
    params:
        # initial HDR detection
        minAltSum: 8  # minimum Alt count to be considered above threshold
        AltRatio: [0.1, .85] # [min max] Alt Ratio in pileup to be considered above threshold / somatic (and not germline)
        # filter HDRs for significance
        MinHDRCount: 1 # minimum lanes around mutation to make it a putative HDR
        MINSIM: .85 # which similarities to consider as HDR
        PAD: 150  # range around mutation to be scanned (if filterbam padding is smaller, that will be used)
        MinAltSupport: 8  # how many mutation reads must be there
EBscore:
    run: true
    pon_path: PON/HAEv7_hg38_NovaSeq # path relative to static path
    pon_list: PON_full.txt # path relative to pon_path
    zero_path: zero  # path relative to pon_path
    use_cache: true
    debug: false
    reflat: false  # reapply flattening procedure to zero file at startup
    PON_output: true
    ABcache_split: 25
    chunksize:  
        EBscore: 5000 # size of zero splits for zerocaching 
        EBcache: 500000  # size of zero splits for zerocaching + size of ponmatrix chunks for stacking
    threads:
        EBcacheMatrix: 10
        EBcacheAB: 24
        EBscore: 20
    params:
        MAPQ: 20      # params for pileup
        Q: 25         # params for pileup
        fit_pen: 0.5  # fitting penalty for beta_binomial parameter finding
        ZDfactor: 9   # how much complexity remains after flattening the tumor-zero lines
        min_zt: 1000  # minimum number of Tzero lines to bother with zero cache
editList:  # all addons to the mutation list after EB/annovar/fisher
    clinscore_yaml: info/clinscoreAML.yaml  # either full path or relative to snakedir            
    candidate_list: info/candidates.xlsx   # either full path or relative to snakedir
filter:
    threads: 1
    run: true
    excel_output: false
    filter1: filter1-AML7 # which custom filter script should be run for filter 1
    filter2: filter2-AML7 # which custom filter script should be run for filter 2
    filter_settings: info/filter_settings.xlsx # the filter file with the filter params # either full path or relative to snakedir
    excel_sheet: AMLMono7 # the sheet in case filter_settings file is xlsx
    keep_syn: true # only applies to the first filter step; in filter2 lists synmuts are always deleted
    keep_UTR: false # only applies to first filter step
    pop_cols:
        - gnomAD_exome_ALL
        - dbSNP153_AltFreq
filter_bam:
    threads: 1
    stringency_for_bam: all # from which filter2 should the filter bam be generated
    stringency_for_IGVnav: moderate
    padding: 200


