---
inputdirs: 
    - /fast/users/szyskam_c/scratch/projects/AllenCell/bamfinal   # source of bam files
workdir: /fast/users/szyskam_c/scratch/projects/AllenCell # here your results are created
samples: # here go all your samples
    samplesheet: sheets/Allen_sheet.csv
    tumor:
        - A
    normal:
        - AICS11_B  # if more than one, the first normal will be used as default for tumor-sample
cleanup: false
configs: 
    general: configs/general/config_Allen.yaml
    CNV: configs/general/config_CNV.yaml