---
inputdirs: 
    - /fast/users/szyskam_c/work/results/NHL/bamfinal   # source of bam files
workdir: /fast/users/szyskam_c/scratch/projects/NHL # here your results are created
samples: # here go all your samples
    samplesheet: sheets/NHL_sheet.csv
    tumor:
        - A  #
        - A1
        - A2 
    normal:
        - B  # if more than one, the first normal will be used as default for tumor-sample
cleanup: false
configs: 
    general: configs/general/config_NHL.yaml
    CNV: configs/general/config_CNV.yaml