---
inputdirs: 
    - /fast/users/szyskam_c/work/testdata/bam # source of bam files
workdir: /fast/users/szyskam_c/scratch/develop/somVarWES # here your results are created
samples: # here go all your samples
    samplesheet: sheets/test_all.csv
    tumor:
        - A  #
        - A1
        - A2 
        - A3
        - A12
    normal:
        - B  # if more than one, the first normal will be used as default for tumor-sample
cleanup: false
configs: 
    general: configs/general/config_AML.yaml
    CNV: configs/general/config_CNV.yaml
